// activity_extension_v2.go: based on the code generated by xsdgen.
// http://www.garmin.com/xmlschemas/ActivityExtensionv2.xsd

package tcx

import "github.com/sio4/geo/xsd"

type ActivityLapExtensiont struct {
	AvgSpeed       float64        `xml:"http://www.garmin.com/xmlschemas/ActivityExtension/v2 AvgSpeed,omitempty"`
	MaxBikeCadence byte           `xml:"http://www.garmin.com/xmlschemas/ActivityExtension/v2 MaxBikeCadence,omitempty"`
	AvgRunCadence  byte           `xml:"http://www.garmin.com/xmlschemas/ActivityExtension/v2 AvgRunCadence,omitempty"`
	MaxRunCadence  byte           `xml:"http://www.garmin.com/xmlschemas/ActivityExtension/v2 MaxRunCadence,omitempty"`
	Steps          uint           `xml:"http://www.garmin.com/xmlschemas/ActivityExtension/v2 Steps,omitempty"`
	AvgWatts       uint           `xml:"http://www.garmin.com/xmlschemas/ActivityExtension/v2 AvgWatts,omitempty"`
	MaxWatts       uint           `xml:"http://www.garmin.com/xmlschemas/ActivityExtension/v2 MaxWatts,omitempty"`
	Extensions     xsd.Extensions `xml:"http://www.garmin.com/xmlschemas/ActivityExtension/v2 Extensions,omitempty"`
}

type ActivityTrackpointExtensiont struct {
	Speed         float64            `xml:"http://www.garmin.com/xmlschemas/ActivityExtension/v2 Speed,omitempty"`
	RunCadence    byte               `xml:"http://www.garmin.com/xmlschemas/ActivityExtension/v2 RunCadence,omitempty"`
	Watts         uint               `xml:"http://www.garmin.com/xmlschemas/ActivityExtension/v2 Watts,omitempty"`
	Extensions    xsd.Extensions     `xml:"http://www.garmin.com/xmlschemas/ActivityExtension/v2 Extensions,omitempty"`
	CadenceSensor CadenceSensorTypet `xml:"CadenceSensor,attr,omitempty"`
}

// May be one of Footpod, Bike
type CadenceSensorTypet string
