// Code generated by xsdgen. DO NOT EDIT.

package tcx

type ProfilePowerZonest struct {
	FTP       uint                `xml:"http://www.garmin.com/xmlschemas/ProfileExtension/v1 FTP,omitempty"`
	PowerZone []ProfilePowerZonet `xml:"http://www.garmin.com/xmlschemas/ProfileExtension/v1 PowerZone"`
}

type ProfilePowerZonet struct {
	Number int  `xml:"http://www.garmin.com/xmlschemas/ProfileExtension/v1 Number"`
	Low    uint `xml:"http://www.garmin.com/xmlschemas/ProfileExtension/v1 Low"`
	High   uint `xml:"http://www.garmin.com/xmlschemas/ProfileExtension/v1 High"`
}
