// garmin_trackpoint_extension_v2.go: based on the code generated by xsdgen.
// http://www.garmin.com/xmlschemas/TrackPointExtensionv2.xsd

package gpx

import "github.com/sio4/geo/xsd"

// This type contains data fields that cannot
// be represented in track points in GPX 1.1 instances.
type TrackPointExtension struct {
	Atemp      float64        `xml:"http://www.garmin.com/xmlschemas/TrackPointExtension/v2 atemp,omitempty"`
	Wtemp      float64        `xml:"http://www.garmin.com/xmlschemas/TrackPointExtension/v2 wtemp,omitempty"`
	Depth      float64        `xml:"http://www.garmin.com/xmlschemas/TrackPointExtension/v2 depth,omitempty"`
	Hr         byte           `xml:"http://www.garmin.com/xmlschemas/TrackPointExtension/v2 hr,omitempty"`
	Cad        byte           `xml:"http://www.garmin.com/xmlschemas/TrackPointExtension/v2 cad,omitempty"`
	Speed      float64        `xml:"http://www.garmin.com/xmlschemas/TrackPointExtension/v2 speed,omitempty"`
	Course     float64        `xml:"http://www.garmin.com/xmlschemas/TrackPointExtension/v2 course,omitempty"`
	Bearing    float64        `xml:"http://www.garmin.com/xmlschemas/TrackPointExtension/v2 bearing,omitempty"`
	Extensions xsd.Extensions `xml:"http://www.garmin.com/xmlschemas/TrackPointExtension/v2 Extensions,omitempty"`
}
