// Code generated by xsdgen. DO NOT EDIT.

package gpx

import "encoding/xml"

// This type provides the ability to extend any data type that includes it.
type Extensionst []string

func (a Extensionst) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	var output struct {
		ArrayType string   `xml:"http://schemas.xmlsoap.org/wsdl/ arrayType,attr"`
		Items     []string `xml:" item"`
	}
	output.Items = []string(a)
	start.Attr = append(start.Attr, xml.Attr{Name: xml.Name{"", "xmlns:ns1"}, Value: "http://www.w3.org/2001/XMLSchema"})
	output.ArrayType = "ns1:anyType[]"
	return e.EncodeElement(&output, start)
}
func (a *Extensionst) UnmarshalXML(d *xml.Decoder, start xml.StartElement) (err error) {
	var tok xml.Token
	for tok, err = d.Token(); err == nil; tok, err = d.Token() {
		if tok, ok := tok.(xml.StartElement); ok {
			var item string
			if err = d.DecodeElement(&item, &tok); err == nil {
				*a = append(*a, item)
			}
		}
		if _, ok := tok.(xml.EndElement); ok {
			break
		}
	}
	return err
}

// This type contains data fields that cannot
// be represented in track points in GPX 1.1 instances.
type TrackPointExtensiont struct {
	Atemp      float64     `xml:"http://www.garmin.com/xmlschemas/TrackPointExtension/v2 atemp,omitempty"`
	Wtemp      float64     `xml:"http://www.garmin.com/xmlschemas/TrackPointExtension/v2 wtemp,omitempty"`
	Depth      float64     `xml:"http://www.garmin.com/xmlschemas/TrackPointExtension/v2 depth,omitempty"`
	Hr         byte        `xml:"http://www.garmin.com/xmlschemas/TrackPointExtension/v2 hr,omitempty"`
	Cad        byte        `xml:"http://www.garmin.com/xmlschemas/TrackPointExtension/v2 cad,omitempty"`
	Speed      float64     `xml:"http://www.garmin.com/xmlschemas/TrackPointExtension/v2 speed,omitempty"`
	Course     float64     `xml:"http://www.garmin.com/xmlschemas/TrackPointExtension/v2 course,omitempty"`
	Bearing    float64     `xml:"http://www.garmin.com/xmlschemas/TrackPointExtension/v2 bearing,omitempty"`
	Extensions Extensionst `xml:"http://www.garmin.com/xmlschemas/TrackPointExtension/v2 Extensions,omitempty"`
}
