// garmin_trackpoint_extension_v2.go: based on the code generated by xsdgen.
// http://www.garmin.com/xmlschemas/TrackPointExtensionv2.xsd

package gpx

import (
	"encoding/xml"

	"github.com/sio4/geo/xsd"
)

// This type contains data fields that cannot be represented in track points
// in GPX 1.1 instances.
type TrackPointExtension struct {
	XMLName xml.Name `xml:"http://www.garmin.com/xmlschemas/TrackPointExtension/v2 TrackPointExtension,omitempty"`

	ATemp      float64        `xml:"atemp,omitempty"`   // degrees celsius
	WTemp      float64        `xml:"wtemp,omitempty"`   // degrees celsius
	Depth      float64        `xml:"depth,omitempty"`   // meters
	HR         uint           `xml:"hr,omitempty"`      // beats per minute
	Cad        uint           `xml:"cad,omitempty"`     // revolutions per minute
	Speed      float64        `xml:"speed,omitempty"`   // meters per second
	Course     float64        `xml:"course,omitempty"`  // degrees in a clockwise direction from the true north line
	Bearing    float64        `xml:"bearing,omitempty"` // degrees in a clockwise direction from the true north line
	Extensions xsd.Extensions `xml:"Extensions,omitempty"`
}
